{"name": "test_mul[failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6.6 == 6.5", "trace": "self = <calculator.testcase.test_calc_case.TestCalc object at 0x000001B3853B04F0>, get_calc = <calculator.python_code.calc.Calculator object at 0x000001B385325A00>\nget_mul_datas = [2.2, 3, 6.5]\n\n    @allure.story(\"乘法测试案例\")\n    @pytest.mark.run(order=3)\n    # @pytest.mark.third\n    def test_mul(self, get_calc, get_mul_datas):\n        \"\"\"\n        get_calc实例化计算器类\n        get_mul_datas:获取测试数据\n        \"\"\"\n        with allure.step(\"计算两个数的积\"):\n            # 获取yaml文件内参数\n            result = get_calc.mul(get_mul_datas[0], get_mul_datas[1])\n            # 如果相加数为float型 ，保留两位小数\n        if isinstance(result, float):\n            result = round(result, 2)\n            # 结果添加断言\n>       assert result == get_mul_datas[2]\nE       assert 6.6 == 6.5\n\ntest_calc_case.py:85: AssertionError"}, "description": "\n        get_calc实例化计算器类\n        get_mul_datas:获取测试数据\n        ", "steps": [{"name": "计算两个数的积", "status": "passed", "start": 1612516764549, "stop": 1612516764549}], "attachments": [{"name": "stdout", "source": "9ea56214-e406-4e8a-9625-07ee99638b6d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_mul_datas", "value": "[2.2, 3, 6.5]"}], "start": 1612516764549, "stop": 1612516764549, "uuid": "b7f75f4d-a474-4523-8738-5b7f8cc77ef8", "historyId": "46d324345c81e20a11708a9afd8faffd", "testCaseId": "419f4dbff296eb8e8298b24764395841", "fullName": "test_calc_case.TestCalc#test_mul", "labels": [{"name": "story", "value": "乘法测试案例"}, {"name": "feature", "value": "测试计算器类"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_case"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-DH8SI2H"}, {"name": "thread", "value": "32452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_case"}]}